### PR TITLE
[build] Almost ported to Dune

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
Actually this is fully ported to Dune, remaining problems are due to true type errors with the Coq API / missing fns (seems like the codebase got kinda corrupted, hard to tell as there is not history in the repos?)

**Comment by agrarpan** [comment]
@ejgallego I've added all the remaining source files, could you help me fix some of the remaining errors please? I can't find the relevant API in a few cases. Thanks!

**Comment by ejgallego** [comment]
Can you please rebase this over the repository it is based?

It is pretty hard to debug code when we don't have a working base version.

**Comment by agrarpan** [comment]
The base repository has a vastly different structure (and uses opam for builds instead of dune), which is why I created a fresh repository. Here's a link to the original repo, if that helps: https://github.com/uwplse/coq-plugin-lib
If not, I can try to recreate this repository starting from there.

**Comment by ejgallego** [comment]
The problem with the creation of the fresh repository is that we have lost the baseline of the working version, as the first commit here doesn't compile.

The code here seems pretty weird, what Coq version is the code supposed to target?

**Comment by agrarpan** [comment]
The original repository is on Coq 8.8 and I'm trying to port to Coq 8.16

**Comment by ejgallego** [comment]
Did you manage to make this code compile with some Coq version?

**Comment by agrarpan** [comment]
The original repo compiles with Coq 8.8

I started with that code and have been trying to fix errors one by one, but have not managed to make it compile yet

**Comment by ejgallego** [comment]
I see two options:
- rebase the changes here over the original 8.8 starting point:
  + migration from make to dune is easy
  + first migrate make -> dune, then redo directory structure
  + then, add a commit porting the code from Coq 8.n to 8.n.+1
- try to fixup the API problems over the current branch for 8.16:

The second approach may be quicker, but YMMV, it is not clear to me how much work still remains to be done in this branch. In the first approach, the advantage is that you always have a working version, and it is easy for devs to suggest changes that are needed.

I see quite a few things to be done for 8.16 to work with the current code:
- `Global.body_of_constant` needs an extra parameter "accessor" (see Coq code for examples)
- Some parts now take an `Econstr.t` instead of a `Constr.t` (should be easy)
- A few errors such as `global_substitution -> Substitution.global_substitution`
- Case expressions got reworked in Coq 8.16 I think (fix not trivial)
- Binders use a different datatype in 8.16 (easy)
- Goal.V82 got removed (commit should explain migration strategy, should not be hard)

**Comment by ejgallego** [comment]
> The original repo compiles with Coq 8.8
> 
> I started with that code and have been trying to fix errors one by one, but have not managed to make it compile yet

You don't want to move to Coq 8.n+1 without fully compiling in Coq 8.n, I'd suggest you indeed try to get the code to compile for 8.8 and Dune first then.

You should be able to get close to 8.15 with the changes you have already here. For the only tricky 8.16 migration thing (Case), you can ask for help in Zulip, or look at the docs.

**Comment by agrarpan** [comment]
Thanks a lot for your help! Will ask on Zulip if I get stuck on something.

**Comment by ejgallego** [comment]
> Thanks a lot for your help! Will ask on Zulip if I get stuck on something.

You are welcome! Good luck, try to see if you get the plugin building in 8.15 indeed first.

**Comment by agrarpan** [comment]
Hi @ejgallego, I have a [commit] (https://github.com/uwplse/coq-plugin-lib/commit/25b372fbacf43bf65d7956e59b1a239fe7deadd7) that builds with Coq 8.9 and uses Dune as the build system. I am trying to port it to Coq 8.10, as you suggested. I've made most (I think) of the fixes required (the subsequent commits in that branch), but am stuck now. Could you please help with this or suggest pointers in the right direction? Thanks!

**Pull request merged**
